use crate::chars::*;

pub fn strip_diacritics(char: &GreekChar) -> &GreekChar {

    if is_consonant(char) { return char }

    match char {
        GreekChar::TwoByte(_, _) => {
            match char {
                &UPPER_ALPHA|&UPPER_ALPHA_WITH_TONOS => &UPPER_ALPHA,
                &UPPER_EPSILON|&UPPER_EPSILON_WITH_TONOS => &UPPER_EPSILON,
                &UPPER_ETA|&UPPER_ETA_WITH_TONOS => &UPPER_ETA,
                &UPPER_IOTA|&UPPER_IOTA_WITH_TONOS|&UPPER_IOTA_WITH_DIALYTIKA => &UPPER_IOTA,
                &UPPER_OMICRON|&UPPER_OMICRON_WITH_TONOS => &UPPER_OMICRON,
                &UPPER_UPSILON|&UPPER_UPSILON_WITH_TONOS|&UPPER_UPSILON_WITH_DIALYTIKA => &UPPER_UPSILON,
                &UPPER_OMEGA|&UPPER_OMEGA_WITH_TONOS => &UPPER_OMEGA,

                &LOWER_ALPHA|&LOWER_ALPHA_WITH_TONOS => &LOWER_ALPHA,
                &LOWER_EPSILON|&LOWER_EPSILON_WITH_TONOS => &LOWER_EPSILON,
                &LOWER_ETA|&LOWER_ETA_WITH_TONOS => &LOWER_ETA,
                &LOWER_IOTA|&LOWER_IOTA_WITH_TONOS|&LOWER_IOTA_WITH_DIALYTIKA|&LOWER_IOTA_WITH_DIALYTIKA_AND_TONOS => &LOWER_IOTA,
                &LOWER_OMICRON|&LOWER_OMICRON_WITH_TONOS => &LOWER_OMICRON,
                &LOWER_UPSILON|&LOWER_UPSILON_WITH_TONOS|&LOWER_UPSILON_WITH_DIALYTIKA|&LOWER_UPSILON_WITH_DIALYTIKA_AND_TONOS => &LOWER_UPSILON,
                &LOWER_OMEGA|&LOWER_OMEGA_WITH_TONOS => &LOWER_OMEGA,
                _ => panic!("Byte sequence does not correspond to a Greek character. If this is a bug, please file an issue. https://github.com/mattrob33/grammateus/issues")
            }
        },
        GreekChar::ThreeByte(_, _, _) => {
            match char {
                &LOWER_ALPHA_WITH_PSILI|&LOWER_ALPHA_WITH_DASIA|&LOWER_ALPHA_WITH_PSILI_AND_VARIA|&LOWER_ALPHA_WITH_DASIA_AND_VARIA|
                &LOWER_ALPHA_WITH_PSILI_AND_OXIA|&LOWER_ALPHA_WITH_DASIA_AND_OXIA|&LOWER_ALPHA_WITH_PSILI_AND_PERISPOMENI|&LOWER_ALPHA_WITH_DASIA_AND_PERISPOMENI|
                &LOWER_ALPHA_WITH_VRACHY|&LOWER_ALPHA_WITH_MACRON|&LOWER_ALPHA_WITH_VARIA_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_YPOGEGRAMMENI|
                &LOWER_ALPHA_WITH_OXIA_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_PERISPOMENI|&LOWER_ALPHA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI|
                &LOWER_ALPHA_WITH_PSILI_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_DASIA_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI|
                &LOWER_ALPHA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI|
                &LOWER_ALPHA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI|
                &LOWER_ALPHA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI|&LOWER_ALPHA_WITH_VARIA|&LOWER_ALPHA_WITH_OXIA => &LOWER_ALPHA,

                &UPPER_ALPHA_WITH_PSILI|&UPPER_ALPHA_WITH_DASIA|&UPPER_ALPHA_WITH_PSILI_AND_VARIA|&UPPER_ALPHA_WITH_DASIA_AND_VARIA|
                &UPPER_ALPHA_WITH_PSILI_AND_OXIA|&UPPER_ALPHA_WITH_DASIA_AND_OXIA|&UPPER_ALPHA_WITH_PSILI_AND_PERISPOMENI|
                &UPPER_ALPHA_WITH_DASIA_AND_PERISPOMENI|&UPPER_ALPHA_WITH_VRACHY|&UPPER_ALPHA_WITH_MACRON|&UPPER_ALPHA_WITH_VARIA|
                &UPPER_ALPHA_WITH_OXIA|&UPPER_ALPHA_WITH_PROSGEGRAMMENI|&UPPER_ALPHA_WITH_PSILI_AND_PROSGEGRAMMENI|&UPPER_ALPHA_WITH_DASIA_AND_PROSGEGRAMMENI|
                &UPPER_ALPHA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI|&UPPER_ALPHA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI|
                &UPPER_ALPHA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI|&UPPER_ALPHA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI|
                &UPPER_ALPHA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI|&UPPER_ALPHA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI => &UPPER_ALPHA,

                &LOWER_EPSILON_WITH_PSILI|&LOWER_EPSILON_WITH_DASIA|&LOWER_EPSILON_WITH_PSILI_AND_VARIA|&LOWER_EPSILON_WITH_DASIA_AND_VARIA|
                &LOWER_EPSILON_WITH_PSILI_AND_OXIA|&LOWER_EPSILON_WITH_DASIA_AND_OXIA|&LOWER_EPSILON_WITH_VARIA|&LOWER_EPSILON_WITH_OXIA => &LOWER_EPSILON,

                &UPPER_EPSILON_WITH_PSILI|&UPPER_EPSILON_WITH_DASIA|&UPPER_EPSILON_WITH_PSILI_AND_VARIA|&UPPER_EPSILON_WITH_DASIA_AND_VARIA|
                &UPPER_EPSILON_WITH_PSILI_AND_OXIA|&UPPER_EPSILON_WITH_DASIA_AND_OXIA|&UPPER_EPSILON_WITH_VARIA|&UPPER_EPSILON_WITH_OXIA => &UPPER_EPSILON,

                &LOWER_ETA_WITH_PSILI|&LOWER_ETA_WITH_DASIA|&LOWER_ETA_WITH_PSILI_AND_VARIA|&LOWER_ETA_WITH_DASIA_AND_VARIA|&LOWER_ETA_WITH_PSILI_AND_OXIA|
                &LOWER_ETA_WITH_DASIA_AND_OXIA|&LOWER_ETA_WITH_PSILI_AND_PERISPOMENI|&LOWER_ETA_WITH_DASIA_AND_PERISPOMENI|&LOWER_ETA_WITH_VARIA_AND_YPOGEGRAMMENI|
                &LOWER_ETA_WITH_YPOGEGRAMMENI|&LOWER_ETA_WITH_OXIA_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_PERISPOMENI|&LOWER_ETA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI|
                &LOWER_ETA_WITH_PSILI_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_DASIA_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI|
                &LOWER_ETA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI|
                &LOWER_ETA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI|&LOWER_ETA_WITH_VARIA|
                &LOWER_ETA_WITH_OXIA => &LOWER_ETA,

                &UPPER_ETA_WITH_PSILI|&UPPER_ETA_WITH_DASIA|&UPPER_ETA_WITH_PSILI_AND_VARIA|&UPPER_ETA_WITH_DASIA_AND_VARIA|&UPPER_ETA_WITH_PSILI_AND_OXIA|
                &UPPER_ETA_WITH_DASIA_AND_OXIA|&UPPER_ETA_WITH_PSILI_AND_PERISPOMENI|&UPPER_ETA_WITH_DASIA_AND_PERISPOMENI|&UPPER_ETA_WITH_VARIA|
                &UPPER_ETA_WITH_OXIA|&UPPER_ETA_WITH_PROSGEGRAMMENI|&UPPER_ETA_WITH_PSILI_AND_PROSGEGRAMMENI|&UPPER_ETA_WITH_DASIA_AND_PROSGEGRAMMENI|
                &UPPER_ETA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI|&UPPER_ETA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI|
                &UPPER_ETA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI|&UPPER_ETA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI|
                &UPPER_ETA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI|&UPPER_ETA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI => &UPPER_ETA,

                &LOWER_IOTA_WITH_PSILI|&LOWER_IOTA_WITH_DASIA|&LOWER_IOTA_WITH_PSILI_AND_VARIA|&LOWER_IOTA_WITH_DASIA_AND_VARIA|&LOWER_IOTA_WITH_PSILI_AND_OXIA|
                &LOWER_IOTA_WITH_DASIA_AND_OXIA|&LOWER_IOTA_WITH_PSILI_AND_PERISPOMENI|&LOWER_IOTA_WITH_DASIA_AND_PERISPOMENI|&LOWER_IOTA_WITH_VRACHY|
                &LOWER_IOTA_WITH_MACRON|&LOWER_IOTA_WITH_DIALYTIKA_AND_VARIA|&LOWER_IOTA_WITH_DIALYTIKA_AND_OXIA|&LOWER_IOTA_WITH_PERISPOMENI|
                &LOWER_IOTA_WITH_DIALYTIKA_AND_PERISPOMENI|&LOWER_IOTA_WITH_VARIA|&LOWER_IOTA_WITH_OXIA => &LOWER_IOTA,

                &UPPER_IOTA_WITH_PSILI|&UPPER_IOTA_WITH_DASIA|&UPPER_IOTA_WITH_PSILI_AND_VARIA|&UPPER_IOTA_WITH_DASIA_AND_VARIA|&UPPER_IOTA_WITH_PSILI_AND_OXIA|
                &UPPER_IOTA_WITH_DASIA_AND_OXIA|&UPPER_IOTA_WITH_PSILI_AND_PERISPOMENI|&UPPER_IOTA_WITH_DASIA_AND_PERISPOMENI|&UPPER_IOTA_WITH_VRACHY|
                &UPPER_IOTA_WITH_MACRON|&UPPER_IOTA_WITH_VARIA|&UPPER_IOTA_WITH_OXIA => &UPPER_IOTA,

                &LOWER_OMICRON_WITH_PSILI|&LOWER_OMICRON_WITH_DASIA|&LOWER_OMICRON_WITH_PSILI_AND_VARIA|&LOWER_OMICRON_WITH_DASIA_AND_VARIA|
                &LOWER_OMICRON_WITH_PSILI_AND_OXIA|&LOWER_OMICRON_WITH_DASIA_AND_OXIA|&LOWER_OMICRON_WITH_VARIA|&LOWER_OMICRON_WITH_OXIA => &LOWER_OMICRON,

                &UPPER_OMICRON_WITH_PSILI|&UPPER_OMICRON_WITH_DASIA|&UPPER_OMICRON_WITH_PSILI_AND_VARIA|&UPPER_OMICRON_WITH_DASIA_AND_VARIA|
                &UPPER_OMICRON_WITH_PSILI_AND_OXIA|&UPPER_OMICRON_WITH_DASIA_AND_OXIA|&UPPER_OMICRON_WITH_VARIA|&UPPER_OMICRON_WITH_OXIA => &UPPER_OMICRON,

                &LOWER_UPSILON_WITH_PSILI|&LOWER_UPSILON_WITH_DASIA|&LOWER_UPSILON_WITH_PSILI_AND_VARIA|&LOWER_UPSILON_WITH_DASIA_AND_VARIA|
                &LOWER_UPSILON_WITH_PSILI_AND_OXIA|&LOWER_UPSILON_WITH_DASIA_AND_OXIA|&LOWER_UPSILON_WITH_PSILI_AND_PERISPOMENI|
                &LOWER_UPSILON_WITH_DASIA_AND_PERISPOMENI|&LOWER_UPSILON_WITH_VRACHY|&LOWER_UPSILON_WITH_MACRON|&LOWER_UPSILON_WITH_DIALYTIKA_AND_VARIA|
                &LOWER_UPSILON_WITH_DIALYTIKA_AND_OXIA|&LOWER_UPSILON_WITH_PERISPOMENI|&LOWER_UPSILON_WITH_DIALYTIKA_AND_PERISPOMENI|&LOWER_UPSILON_WITH_VARIA|
                &LOWER_UPSILON_WITH_OXIA => &LOWER_UPSILON,

                &UPPER_UPSILON_WITH_DASIA|&UPPER_UPSILON_WITH_DASIA_AND_VARIA|&UPPER_UPSILON_WITH_DASIA_AND_OXIA|&UPPER_UPSILON_WITH_DASIA_AND_PERISPOMENI|
                &UPPER_UPSILON_WITH_VRACHY|&UPPER_UPSILON_WITH_MACRON|&UPPER_UPSILON_WITH_VARIA|&UPPER_UPSILON_WITH_OXIA => &UPPER_UPSILON,

                &LOWER_OMEGA_WITH_PSILI|&LOWER_OMEGA_WITH_DASIA|&LOWER_OMEGA_WITH_PSILI_AND_VARIA|&LOWER_OMEGA_WITH_DASIA_AND_VARIA|
                &LOWER_OMEGA_WITH_PSILI_AND_OXIA|&LOWER_OMEGA_WITH_DASIA_AND_OXIA|&LOWER_OMEGA_WITH_PSILI_AND_PERISPOMENI|&LOWER_OMEGA_WITH_DASIA_AND_PERISPOMENI|
                &LOWER_OMEGA_WITH_VARIA_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_OXIA_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_PERISPOMENI|
                &LOWER_OMEGA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_PSILI_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_DASIA_AND_YPOGEGRAMMENI|
                &LOWER_OMEGA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI|
                &LOWER_OMEGA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI|
                &LOWER_OMEGA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI|&LOWER_OMEGA_WITH_VARIA|
                &LOWER_OMEGA_WITH_OXIA => &LOWER_OMEGA,

                &UPPER_OMEGA_WITH_PSILI|&UPPER_OMEGA_WITH_DASIA|&UPPER_OMEGA_WITH_PSILI_AND_VARIA|&UPPER_OMEGA_WITH_DASIA_AND_VARIA|
                &UPPER_OMEGA_WITH_PSILI_AND_OXIA|&UPPER_OMEGA_WITH_DASIA_AND_OXIA|&UPPER_OMEGA_WITH_PSILI_AND_PERISPOMENI|&UPPER_OMEGA_WITH_DASIA_AND_PERISPOMENI|
                &UPPER_OMEGA_WITH_VARIA|&UPPER_OMEGA_WITH_OXIA|&UPPER_OMEGA_WITH_PROSGEGRAMMENI|&UPPER_OMEGA_WITH_PSILI_AND_PROSGEGRAMMENI|
                &UPPER_OMEGA_WITH_DASIA_AND_PROSGEGRAMMENI|&UPPER_OMEGA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI|&UPPER_OMEGA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI|
                &UPPER_OMEGA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI|&UPPER_OMEGA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI|
                &UPPER_OMEGA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI|&UPPER_OMEGA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI => &UPPER_OMEGA,

                &LOWER_RHO_WITH_PSILI|&LOWER_RHO_WITH_DASIA => &LOWER_RHO,

                &UPPER_RHO_WITH_DASIA => &UPPER_RHO,

                _ => panic!("Byte sequence does not correspond to an extended Greek character. If this is a bug, please file an issue. https://github.com/mattrob33/grammateus/issues")
            }
        }
    }
}